### ISSUE TITLE
importing plotting from nilearn is not consistent across the lesson

### ISSUE THREAD

**Issue by dpshelio** [carpentries-incubator/SDC-BIDS-fMRI#17]
For example, sometimes ([ep 6](https://github.com/carpentries-incubator/SDC-BIDS-fMRI/blob/gh-pages/_episodes/06-apply-a-parcellation.md)) it's imported as:
```python
from nilearn import plotting
```
where others ([ep 3](https://github.com/carpentries-incubator/SDC-BIDS-fMRI/blob/gh-pages/_episodes/03-basic_image_manipulation.md), [ep 4](https://github.com/carpentries-incubator/SDC-BIDS-fMRI/blob/gh-pages/_episodes/04-integrating_functional_data.md), [ep 7](https://github.com/carpentries-incubator/SDC-BIDS-fMRI/blob/gh-pages/_episodes/07-functional-connectivity-analysis.md)) do:
```python
from nilearn import plotting as plot
```
In one case ([ep 5](https://github.com/carpentries-incubator/SDC-BIDS-fMRI/blob/gh-pages/_episodes/05-data-cleaning-with-nilearn.md)), it's aliased as `plt` but then `matplotlib.pyplot` uses `plt` too.

**Comment by jerdra** [comment]
Hi @dpshelio!

Thanks for pointing this out! I think you make a good point about avoiding any confusion with `pyplot`. I think having a consistent import convention across all `nilearn` modules in general would be a good idea:

`nilearn.image` --> `nimg`
`nilearn.plotting` --> `nplot`
`nilearn.signal` --> `nsig` 

Lmk if you'd like to contribute this as a PR
